export const FORBIDDEN_TERMS = [
  "patient",
  "diagnos",
  "treat",
  "cure",
  "medical device",
  "medical",
  "clinical",
  "prescription",
  "medication",
  "drug",
  "heal",
  "therapy",
  "symptom",
  "clinical finding",
  "medical result",
  "reduces inflammation",
  "we heal",
] as const;

export const PREFERRED_REPLACEMENTS: Record<string, string> = {
  patient: "client",
  diagnos: "assessment",
  treat: "support",
  cure: "support",
  "medical device": "wellness platform",
  medical: "recovery",
  clinical: "wellness",
  prescription: "session guidance",
  medication: "wellness support",
  drug: "wellness support",
  heal: "recover",
  therapy: "recovery support",
  symptom: "recovery signal",
  "clinical finding": "movement insight",
  "medical result": "wellness indicator",
  "reduces inflammation": "supports inflammation management",
  "we heal": "the body heals itself",
};
