import type { BodyRegion } from "../types/client-profile.js";
import type { PadPlacement } from "../types/recovery-intelligence.js";

export const PAD_PLACEMENT_MAP: Record<BodyRegion, PadPlacement> = {
  right_shoulder: {
    sunRegion: 'Right anterior deltoid / upper trapezius',
    moonRegion: 'Right posterior deltoid / infraspinatus',
    leftFuncs: ['leftHotRed', 'leftColdBlue', 'leftHotRed'],
    rightFuncs: ['rightColdBlue', 'rightHotRed', 'rightColdBlue'],
    rationale: 'Sun pad warms the anterior shoulder to promote circulation; Moon pad cools the posterior shoulder to support recovery.',
  },
  left_shoulder: {
    sunRegion: 'Left anterior deltoid / upper trapezius',
    moonRegion: 'Left posterior deltoid / infraspinatus',
    leftFuncs: ['leftColdBlue', 'leftHotRed', 'leftColdBlue'],
    rightFuncs: ['rightHotRed', 'rightColdBlue', 'rightHotRed'],
    rationale: 'Sun pad warms the anterior shoulder to promote circulation; Moon pad cools the posterior shoulder to support recovery.',
  },
  right_hip: {
    sunRegion: 'Right hip flexor / TFL',
    moonRegion: 'Right gluteus medius',
    leftFuncs: ['leftHotRed', 'leftColdBlue', 'leftHotRed'],
    rightFuncs: ['rightColdBlue', 'rightHotRed', 'rightColdBlue'],
    rationale: 'Sun pad warms hip flexor to support mobility; Moon pad cools gluteus medius for recovery balance.',
  },
  left_hip: {
    sunRegion: 'Left hip flexor / TFL',
    moonRegion: 'Left gluteus medius',
    leftFuncs: ['leftColdBlue', 'leftHotRed', 'leftColdBlue'],
    rightFuncs: ['rightHotRed', 'rightColdBlue', 'rightHotRed'],
    rationale: 'Sun pad warms hip flexor to support mobility; Moon pad cools gluteus medius for recovery balance.',
  },
  lower_back: {
    sunRegion: 'Lumbar paraspinals (L3–L5)',
    moonRegion: 'Sacroiliac region',
    leftFuncs: ['leftHotRed', 'leftColdBlue', 'leftHotRed'],
    rightFuncs: ['rightColdBlue', 'rightHotRed', 'rightColdBlue'],
    rationale: 'Sun pad warms lumbar paraspinals to support mobility; Moon pad cools sacroiliac region. Region-specific safe limits applied.',
  },
  upper_back: {
    sunRegion: 'Thoracic paraspinals (T4–T8)',
    moonRegion: 'Rhomboid / mid-trapezius',
    leftFuncs: ['leftHotRed', 'leftColdBlue', 'leftHotRed'],
    rightFuncs: ['rightColdBlue', 'rightHotRed', 'rightColdBlue'],
    rationale: 'Sun pad warms thoracic spine to support posture recovery; Moon pad cools rhomboid area.',
  },
  right_knee: {
    sunRegion: 'Right quadriceps / VMO',
    moonRegion: 'Right popliteal / hamstring insertion',
    leftFuncs: ['leftHotRed', 'leftColdBlue', 'leftHotRed'],
    rightFuncs: ['rightColdBlue', 'rightHotRed', 'rightColdBlue'],
    rationale: 'Sun pad warms quadriceps to support knee mobility; Moon pad cools posterior knee.',
  },
  left_knee: {
    sunRegion: 'Left quadriceps / VMO',
    moonRegion: 'Left popliteal / hamstring insertion',
    leftFuncs: ['leftColdBlue', 'leftHotRed', 'leftColdBlue'],
    rightFuncs: ['rightHotRed', 'rightColdBlue', 'rightHotRed'],
    rationale: 'Sun pad warms quadriceps to support knee mobility; Moon pad cools posterior knee.',
  },
  neck: {
    sunRegion: 'Posterior cervical / upper trapezius',
    moonRegion: 'Lateral cervical / levator scapulae',
    leftFuncs: ['leftHotRed', 'leftColdBlue', 'leftHotRed'],
    rightFuncs: ['rightColdBlue', 'rightHotRed', 'rightColdBlue'],
    rationale: 'Gentle warming on posterior neck supports tension release; cooling on lateral neck supports comfort. Region-specific safe limits applied.',
  },
  right_calf: {
    sunRegion: 'Right gastrocnemius',
    moonRegion: 'Right soleus / Achilles region',
    leftFuncs: ['leftHotRed', 'leftColdBlue', 'leftHotRed'],
    rightFuncs: ['rightColdBlue', 'rightHotRed', 'rightColdBlue'],
    rationale: 'Sun pad warms gastrocnemius for circulation; Moon pad cools lower calf.',
  },
  left_calf: {
    sunRegion: 'Left gastrocnemius',
    moonRegion: 'Left soleus / Achilles region',
    leftFuncs: ['leftColdBlue', 'leftHotRed', 'leftColdBlue'],
    rightFuncs: ['rightHotRed', 'rightColdBlue', 'rightHotRed'],
    rationale: 'Sun pad warms gastrocnemius for circulation; Moon pad cools lower calf.',
  },
  right_arm: {
    sunRegion: 'Right biceps / anterior forearm',
    moonRegion: 'Right triceps / posterior forearm',
    leftFuncs: ['leftHotRed', 'leftColdBlue', 'leftHotRed'],
    rightFuncs: ['rightColdBlue', 'rightHotRed', 'rightColdBlue'],
    rationale: 'Sun pad warms anterior arm; Moon pad cools posterior arm for balanced recovery.',
  },
  left_arm: {
    sunRegion: 'Left biceps / anterior forearm',
    moonRegion: 'Left triceps / posterior forearm',
    leftFuncs: ['leftColdBlue', 'leftHotRed', 'leftColdBlue'],
    rightFuncs: ['rightHotRed', 'rightColdBlue', 'rightHotRed'],
    rationale: 'Sun pad warms anterior arm; Moon pad cools posterior arm for balanced recovery.',
  },
  right_foot: {
    sunRegion: 'Right plantar fascia / arch',
    moonRegion: 'Right dorsal foot / ankle',
    leftFuncs: ['leftHotRed', 'leftColdBlue', 'leftHotRed'],
    rightFuncs: ['rightColdBlue', 'rightHotRed', 'rightColdBlue'],
    rationale: 'Sun pad warms plantar surface; Moon pad cools dorsal foot.',
  },
  left_foot: {
    sunRegion: 'Left plantar fascia / arch',
    moonRegion: 'Left dorsal foot / ankle',
    leftFuncs: ['leftColdBlue', 'leftHotRed', 'leftColdBlue'],
    rightFuncs: ['rightHotRed', 'rightColdBlue', 'rightHotRed'],
    rationale: 'Sun pad warms plantar surface; Moon pad cools dorsal foot.',
  },
};
